# Generated by Django 5.2 on 2025-04-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0003_disponibilidadehorarios_data_inicial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorados',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='mentorados',
            name='token',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
