# Generated by Django 5.2 on 2025-04-13 20:14

from django.db import migrations, models
import datetime



class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0004_remove_mentorados_criado_em_mentorados_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorados',
            name='criado_em',
            field=models.DateField(auto_now_add=True, default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
    ]
