# Generated by Django 5.2 on 2025-04-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0005_mentorados_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorados',
            name='criado_em',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
